### ISSUE TITLE
Library is not compatible with all PSR-18 clients

### ISSUE THREAD

**Issue by clamburger** [teamreflex/ChallongePHP#13]
The following lines in `ClientWrapper.php` use a Guzzle-specific call that does not work with a standard PSR-18 client:

https://github.com/teamreflex/ChallongePHP/blob/470f7f04c6d9842bbc33878d28487bde2df92e72/src/Challonge/ClientWrapper.php#L55-L61

For example, when used with the Symfony HTTP client, I receive this error:
`Attempted to call an undefined method named "request" of class "Symfony\Component\HttpClient\Psr18Client". `

The best approach would be to pass down a `RequestFactoryInterface` (as defined in [PSR-17](https://www.php-fig.org/psr/psr-17/)) in order to construct a PSR-7 request. This might require a breaking change to the `Challonge` class, so an alternative option could be to add a dependency on a specific [PSR-7 implementation](https://packagist.org/providers/psr/http-message-implementation) and construct the request object directly. In both cases, you would then pass that request object to `$this->client->sendRequest()`.

**Comment by xKairu** [comment]
That's awkward, serves me right for just assuming it'd work. Just pushed a fix to master, let me know if that fixes it and I'll tag it.

**Comment by clamburger** [comment]
Pulled from master and it looks good to me 👍

**Comment by xKairu** [comment]
Tagged at 3.1, thanks for the heads up 😊
